### ISSUE TITLE
pear installation fails.

### ISSUE THREAD

**Issue by madtechsupport** [char0n/ffmpeg-php#24]
Following the steps here https://github.com/CodeScaleInc/ffmpeg-php.

$ sudo pear channel-discover pear.codescale.net
$ sudo pear install codescale/FFmpegPHP2
downloading FFmpegPHP2-2.7.0.tgz ...
Starting to download FFmpegPHP2-2.7.0.tgz (1,541,863 bytes)
.................................................................................................................................................................................................................................................................................................................done: 1,541,863 bytes
could not extract the package.xml file from "/build/buildd/php5-5.5.9+dfsg/pear-build-download/FFmpegPHP2-2.7.0.tgz"
Download of "codescale/FFmpegPHP2" succeeded, but it is not a valid package archive
Error: cannot download "codescale/FFmpegPHP2"
Download failed
install failed

**Comment by char0n** [comment]
We no longer support pear installations. Use packagist instead

https://packagist.org/packages/char0n/ffmpeg-php#dev-master
