### ISSUE TITLE
Thumbnails with only width or height specified

### ISSUE THREAD

**Issue by meliody** [char0n/ffmpeg-php#26]
I had problems with getFrameAtTime() when handling files with varying aspect ratio.
The getFrameAtTime() function stretches the thumbnails.
It happens here.

```
$image_size = ' -s '.$width.'x'.$height;
```

A quick line of code cold change this:

```
$image_size = " -vf \"scale=$width:$height\" ";
```

Thus a call like

```
getFrameAtTime(4,60,-1,5,'correct_aspect_ratio.jpg')
```

would result in an image that's always 60px in width and dynamic height, according to the a/r.
I did not test the performance impact of my proposal - but it should not be too bad.
One could also think of implementing the -crop filter in order to archive fixed size images.
But that's a bit more complicated.

**Comment by char0n** [comment]
Thanks,

But I think there is bug in the code, specifically that method signature is declared as such:

public function getFrameAtTime($seconds = null, $width = null, $height = null, $quality = null, $frameFilePath = null, &$output = null) 


But is called with wrong parameters:

$frame = $this->getFrameAtTime($frameTime, $height, $width, $quality);

As you can see $height and $with are mixed up. Width should be first. May this be the cause of your issue ?

**Comment by char0n** [comment]
I have fixed the order of the params. Try using the source code from current master branch or use 2.8.1 release.
