### ISSUE TITLE
This wont run on my mac and I have FFMPeg installed

### ISSUE THREAD

**Issue by OElesin** [char0n/ffmpeg-php#28]
Fatal error: Uncaught exception 'Exception' with message 'FFmpeg is not installed on host server' in /Applications/XAMPP/xamppfiles/htdocs/ffmpeg-php-master/provider/FFmpegOutputProvider.php:50 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/ffmpeg-php-master/FFmpegMovie.php(220): FFmpegOutputProvider->getOutput() #1 /Applications/XAMPP/xamppfiles/htdocs/ffmpeg-php-master/FFmpegMovie.php(209): FFmpegMovie->setProvider(Object(FFmpegOutputProvider)) #2 /Applications/XAMPP/xamppfiles/htdocs/t.php(11): FFmpegMovie->__construct('/Applications/X...') #3 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/ffmpeg-php-master/provider/FFmpegOutputProvider.php on line 50

**Comment by char0n** [comment]
May be related to https://github.com/CodeScaleInc/ffmpeg-php/issues/27

**Comment by orlleite** [comment]
I have to put the complete path to ffmpeg: /usr/local/bin/ffmpeg

If you have problem with DYLD_LIBRARY_PATH use this: 
```
exec('unset DYLD_LIBRARY_PATH ;');
putenv('DYLD_LIBRARY_PATH');
putenv('DYLD_LIBRARY_PATH=/usr/bin');
```
[SO answer](http://stackoverflow.com/questions/24941078/ffmpeg-and-php-on-mac-doest-work)

**Comment by char0n** [comment]
Closing this. @orlleite thanks for providing advice. @OElesin hoped it helped you.

**Comment by pokepud3** [comment]
I'm having the same issue. I did define the 
public function __construct($ffmpegBinary = '/home/user/bin/ffmpeg', $persistent = false) {

The version Im using is ffmpeg version N-84660-gd92ad42 , does it not being a number have anything to do with the issue? just typing ffmpeg or the above directory/ffmpeg shows the ffmpeg information just fine via command line but no luck on this end. Thanks

**Comment by char0n** [comment]
@pokepud3

**Comment by pokepud3** [comment]
Yes just grabbed it from the tarball. 2.9.0

**Comment by char0n** [comment]
Then I guess it's a problem of parsing output of your version of ffmpeg. This library is currently tested on 3.2.2 ffmpeg version and on this version it works like a charm.

What is behind the cryptic N-84660-gd92ad42 ? I tried to search for commit hash of this version but no success https://github.com/FFmpeg/FFmpeg/commit/gd92ad42.

**Comment by pokepud3** [comment]
I installed it using this: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu. Latest snapshot build. 

wget http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 Latest snapshot from ffmpeg. Installed it yesterday. That's just how they are named.

**Comment by char0n** [comment]
Install 3.2.2 version and everything should work as expected. This is the latest version this library is tested against. If for any reason you need higher ffmpeg binary version, it is possible that this library works as well but from what you are reporting it seems like ffmpeg binary changed its output and our parser cannot compensate. It will take some time until we support latest ffmpeg version 3.2.4.

**Comment by pokepud3** [comment]
I'm fairly sure that's it. Will do. Thanks!

**Comment by char0n** [comment]
See the build log here: https://circleci.com/gh/char0n/ffmpeg-php/56?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It show how we install ffmpeg binary to test it on ubuntu. The key is here:

```sudo add-apt-repository ppa:mc3man/trusty-media -y```

**Comment by pokepud3** [comment]
Tried it with ffmpeg 3.2.2 with the same error.  Does the files need to be in the same directory as ffmpeg? 

ffmpeg version 3.2.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609

Fatal error: Uncaught Exception: FFmpeg is not installed on host server in /home/ftp/files/ffmpeg-php/provider/FFmpegOutputProvider.php:50

**Comment by char0n** [comment]
Hi again, then I guess it has something to do with how macOS passes output from its processes to php script. There something non standard there. 

ffmpeg-php is almost 8 years old project so it can be tested on older PHPUnit versions only. Use e.g. PHPUnit 3.7.18 to make it run. We are already working on PSR-4 compliant version of ffmpeg-php here https://github.com/char0n/ffmpeg-php/tree/PSR-4-develop. Just be patient ;]

I guess in your case, it is about finding out why $output is empty: https://github.com/char0n/ffmpeg-php/blob/PSR-4-develop/src/OutputProviders/FFMpegProvider.php#L53

I will be something platform specific. I cannot do it for you, I don't have a macOS system. Can you do it ? I can guide you through.

**Comment by pokepud3** [comment]
I just noticed that this thread is for mac. I'm not using a mac. I'm using Ubuntu 16 LTS.  I can provide you my login info for the server, if you want to take a quick look.

**Comment by char0n** [comment]
Well why not. I guess I can squeeze 10 minutes tonight to have a look at it. 

vladimir.gorej@gmail.com

**Comment by char0n** [comment]
Resolved. Permission issue.

**Comment by char0n** [comment]
@mayoalexander to tell you the truth I don't remember. It's been 4 years since this issue. Can you describe what problems are you seeing specifically?

**Comment by mayoalexander** [comment]
@char0n im getting the same "ffmpeg is not installed on the host server." you mentioned it might be a permissions issue; i used another solution that ran ffmpeg via an exec() & system() function, so i know FFMPEG is installed. im assuming it must be something with the code trying to reach something it doesnt have permission to. 

I also reached out to GoDaddy about the note you listed in the Readme about the partnership. Unfortunately they were not familiar with with the package :( 

Feel free to email me if you'd like alex@freelabel.net

**Comment by char0n** [comment]
@mayoalexander the library is running `ffmepg` via `exec` as well. It's assuming the name of the binary is [ffmpeg](https://github.com/char0n/ffmpeg-php/blob/master/src/OutputProviders/FFMpegProvider.php#L17).

We need to debug [FFMpegProvider](https://github.com/char0n/ffmpeg-php/blob/master/src/OutputProviders/FFMpegProvider.php) class and find out if the detection of ffmpeg works. What is the version of ffmpeg you're using?

**Comment by olimjonelmurodov** [comment]
In my case `exec()` was in `php.ini`'s `disable_functions` list. Commenting `disable_functions` helped fix this.
