### ISSUE TITLE
Tarball empty

### ISSUE THREAD

**Issue by commonpike** [char0n/ffmpeg-php#29]
The tarball mentioned in the README

> wget http://github.com/char0n/ffmpeg-php/tarball/master

is actually empty except for a readme. 
ofcourse, people can download the zip instead. just saying.

**Comment by char0n** [comment]
Thanks, I'll check it out today evening.

**Comment by commonpike** [comment]
Must say, so happy to find this repo. Zillion thanks!

**Comment by char0n** [comment]
Well, god knows if the code is still up-to-date to newer versions of ffmpeg.

On Thu, Apr 7, 2016 at 3:09 PM, pike <notifications@github.com> wrote:

> Must say, so happy to find this repo. Zillion thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeScaleInc/ffmpeg-php/issues/29#issuecomment-206891056>
>



-- 

Vladimír Gorej | CodeScale s.r.o.
email: gorej@codescale.net
tel: +420 777 861 279, +421 948 023 011
web: http://www.codescale.net

**Comment by commonpike** [comment]
It seemlessly works as a stub for the package (which is no longer in the linux distro). not sure what functionality is being used .. i just popped in your php and it worked :-)

**Comment by char0n** [comment]
Problem fixed
