### ISSUE TITLE
Audio/ClipFilter

### ISSUE THREAD

**Issue by sjoerdstaal** [char0n/ffmpeg-php#31]
I was not able to Clip an audio file, but when I created ClipFilter in Audio from the ClipFilter in Video, it worked, (for mp3 at least), maybe an idea to include in the code?

**Comment by char0n** [comment]
Can you provide pull request ? I did not think of usecase clipping an audio file.

**Comment by char0n** [comment]
@sjoerdstaal can you provide source code so that I could image what were you doing ?

**Comment by char0n** [comment]
Closing this. Insufficient info to act further.
