### ISSUE TITLE
Edit audio

### ISSUE THREAD

**Issue by camilo246800** [char0n/ffmpeg-php#40]
Hello! Thank you very much for the library.

I have a rookie doubt. I know how to manage audios in the old ffmpeg-php library. For the documentation.

But here it is not very clear :( Where can I see examples or docs?

I want to cut audios, join and change formats.

Thank you!

**Comment by char0n** [comment]
Hello, 

API documentation is available at https://char0n.github.io/ffmpeg-php/namespaces/Char0n.FFMpegPHP.html

Regarding examples; the best examples we have is to check our tests - https://github.com/char0n/ffmpeg-php/tree/master/tests

**Comment by camilo246800** [comment]
Thank you! In fact I had already entered this documentation, but I did not see direct information about audios.

Excuse the hazing, I'm very new with ffmpeg.

**Comment by char0n** [comment]
Did the examples in tests help you case ?

**Comment by camilo246800** [comment]
Thank you! I managed to catch up with the general and other functions of the Movie object.

I just can not find how to cut or join audios. Try to guide me with the original library and add compatibility but I'm not doing it right.

Any way to go? Thank you!

**Comment by char0n** [comment]
How would you do this audio joinin in original ffmpeg-php ? Pls provide the code and I'll provide the code how to do that in new ffmpeg-php

**Comment by camilo246800** [comment]
Hello Char!

Thanks for the support! What I want to achieve is to be able to split an audio into 2 or more parts and join audio files. With that I would be happy!

In this way, it would be done with the old API.

`<?php

require 'vendor/autoload.php';
use FFMpeg\Format\Audio\Mp3;
use FFMpeg\Media\Video;
use FFMpeg\Media\Audio;
    
$ffmpeg = FFMpeg\FFMpeg::create(array(
    'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
    'ffprobe.binaries' => '/usr/bin/ffprobe'
));

//Cut audio in x seconds.

$audio->filters()->clip(FFMpeg\Coordinate\TimeCode::fromSeconds(30), FFMpeg\Coordinate\TimeCode::fromSeconds(15));

// Set an audio format
$audio_format = new FFMpeg\Format\Audio\Mp3();

// Extract the audio into a new file as mp3
$audio->save($audio_format, 'result.mp3');

//------------------------------------------------------------

//Concatenations audio files
        
        $files = [
            __DIR__ . '/../files/Jahzzar_-_05_-_Siesta.mp3',
            __DIR__ . '/../files/02_-_Favorite_Secrets.mp3',
        ];

        $audio = $ffmpeg->open(reset($files));

        assertInstanceOf('FFMpeg\Media\Audio', $audio);
        
        $filename = 'concat-output.mp3';

        $audio->concat($files)->saveFromSameCodecs($filename, TRUE);
?>`

Thanks for the help!

**Comment by char0n** [comment]
Hello @camilo246800,

Now I get it. I think you mistook this library for a different one. This library is a pure port of PHP extesion that lived here: http://ffmpeg-php.sourceforge.net/

This library never had API you describe and was implemented to handle different problem then Video/Audio manipulations. This library is about getting metadata from the Video or Audio files.

**Comment by camilo246800** [comment]
Woo, there was confusion. Thank you!
