### ISSUE TITLE
I can upload video on my computer as server with installed ffmpeg but when I use go daddy as server I could not upload the video  even I used the ffmpeg extension in godaddy

### ISSUE THREAD

**Issue by summerraod** [char0n/ffmpeg-php#41]

**Comment by char0n** [comment]
Hi @summerraod,

Not sure I understand your issue with the library. Can you elaborate more please?

**Comment by summerraod** [comment]
I installed ffmpeg on my website to reduce the file size, initially I used
my windows 10 computer as my server so I could access my website outside of
my home network, it was doing fine for a month I uploaded videos and it
worked well. But I don't know what happened maybe ISP blocked the port 80
suddenly could not access my server outside so I decided to use godaddy but
then I could not able to upload videos in godaddy even I checked the ffmpeg
option in php extensions. This is the code:
"ffmpeg -i $imageTmp_Name -b:v $bitrate -bufsize $bitrate
$targetDirVid.mp4".

Thank you.

**Comment by char0n** [comment]
I don't think your problem has anything to do with this library. This library is PHP wrapper around [ffmpeg](https://ffmpeg.org/).

**Comment by summerraod** [comment]
I agree it must be the settings in godaddy but it was hard to talk to them.
In my localhost it was working fine. Thank you.

**Comment by char0n** [comment]
Sorry I cannot help more, I can give support on this library but cannot resolve problems with GoDaddy.
