### ISSUE TITLE
go daddy ffmpeg path to binary

### ISSUE THREAD

**Issue by lakland89** [char0n/ffmpeg-php#44]
hello I'm trying to find the path to ffmpeg binary.  Im using peeps and its asking me for that, I already have the ffmpeg 4.3 version installed. Can anyone help me please.

**Comment by char0n** [comment]
Hi, 

ffmpeg binary should be preinstalled on godaddy machine. This library should be preinstalled and set in `include_path` as well.
Then usage like this should be possible. Don't have much details about how GoDaddy uses this library, but I could request this information and document in README.

```php
use Char0n\FFMpegPHP\Movie;

$movie = new Movie('./test.mp4');
var_dump($movie->getDuration());
