### ISSUE TITLE
Can we use without FFMPEG extension installations

### ISSUE THREAD

**Issue by ahaomar** [char0n/ffmpeg-php#48]
Can we use without FFMPEG extension installations

**Comment by char0n** [comment]
Yes, this is pure PHP code that only needs [ffmpeg](https://www.ffmpeg.org/) installed on the system.

**Comment by ahaomar** [comment]
No. i mean my hosting does not allow to install ffmpeg extension on server so without installation can i use that ? I am using Penthon https://pantheon.io/docs/faq#do-you-support-ffmpeg-transcoding where its not allowed

**Comment by char0n** [comment]
Then the answer is no. Without ffmpeg installed on the system, this library will not work.

**Comment by ahaomar** [comment]
any alternative please ? i just need for thumbnail generation of mp4 files

**Comment by char0n** [comment]
You could you third-party transcoding service as pantheon suggest. The only one I worked with and can (kind of) recommend is https://cloud.qencode.com/.
