### ISSUE TITLE
AnimatedGifTest does not comply with PSR-4

### ISSUE THREAD

**Issue by ToshY** [char0n/ffmpeg-php#53]
**Problem**

When installing with composer

```
Class Char0n\FFMpegPHP\Tests\FFmpegAnimatedGifTest located in ./vendor/char0n/ffmpeg-php/tests/AnimatedGifTest.php does not comply with psr-4 autoloading standard. Skipping.
```

File is named `AnimatedGifTest.php` but the class is named `FFmpegAnimatedGifTest`.

**Suggestion**

Rename class to `AnimatedGifTest.php`

**Comment by char0n** [comment]
Thanks for noticing this. 

Additional question here. IMHO it doesn't make sense to distribute test files via composer. Not sure what conventions are used in PHP/composer ecosystem now, but what you say for excluding tests from composer archive? https://getcomposer.org/doc/04-schema.md#archive (I'll create a separate issue if you tell me that it makes sense)
