### ISSUE TITLE
Publicly accessible URLs throw exception

### ISSUE THREAD

**Issue by ToshY** [char0n/ffmpeg-php#55]
**Problem**

FFmpeg is capable of getting video information through (publicly accessible) URLs. Currently both the `FFProbeProvider` and `FFMpegProvider` include a `!file_exists` to check if a file exists on the current file system.

**Suggestion**

Change `file_exists` to `file`.

**Comment by char0n** [comment]
Hi @ToshY,

Though I do like the possibility of reading the remote file using URL, there are certain implications of using `file()` function.

```
Returns the file in an array. Each element of the array corresponds to a line in the file, with the newline still attached. Upon failure, file() returns false.

Source: https://www.php.net/manual/en/function.file.php
``` 
Using `file()` function means, that entire multimedia file is fetched into memory and presented to PHP as an array. This may crash the PHP process for big multimedia files (depends on PHP configuration on system).

How about using [file_get_contents](https://www.php.net/manual/en/function.file-get-contents.php)? This functions opens the file as a stream and we can use `offset/length` to just read one byte or test for `false`. Seems to me that this function better expresses your original intention without compromising this library stability.

**Comment by ToshY** [comment]
Oh I didn't think of that. Yeah, seems that `file_get_contents` would be better suited.
