### ISSUE TITLE
ООП

### ISSUE THREAD

**Issue by BuslikDrev** [char0n/ffmpeg-php#60]
Почему нельзя нормально написать ОПП, чтобы люди просто скопировали в свой проект https://github.com/char0n/ffmpeg-php/tree/master/src

```
require_once  'src/Movie.php';

$movie = new Movie('test.mp4');
var_dump($movie->getDuration());
```

**Comment by char0n** [comment]
Hi @BuslikDrev,

Could you use English please? I don't read azbuka or cyrillic alphabets nor understand the language encoded in it.
