### ISSUE TITLE
Video thumbnails broken due to use of imagegd2  function

### ISSUE THREAD

**Issue by timbykov** [char0n/ffmpeg-php#61]
In Versoin 2.3.3 of GD library for php, the GD2 image support has been disabled, you have to custom compile your own php version to enable this support
https://github.com/libgd/libgd/issues/428

the call to imagegd2($gdImage) in function gdImageToBinaryData($gdImage) function no longer works, resulting

Warning: imagegd2(): GD2 image support has been disabled 

Please replace with imagejpeg($gdImage) instead of imagegd2

**Comment by char0n** [comment]
@timbykov,

Thanks, would you mind issuing a PR to fix this?

**Comment by char0n** [comment]
Fixed in https://github.com/char0n/ffmpeg-php/releases/tag/3.2.1
